package com.example;

import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;
import java.util.Optional;

import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.TextInputDialog;

public class PrimaryController {

    @FXML
    private DatePicker datePicker;

    @FXML
    private ComboBox<String> timeSlots;


    // Database credentials
    private static final String DB_URL = "jdbc:mysql://localhost:3306/appointment_app";
    private static final String DB_USER = "root"; // Replace with your username
    private static final String DB_PASSWORD = "MYSQLpassword"; // Replace with your password

    @FXML
    public void initialize() {
        // Add the times to the drop-down menu in the combo box
        timeSlots.getItems().addAll("9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "13:00 PM","13:30 PM", "14:00 PM", "14:30 PM", "15:00 PM", "15:30 PM", "16:00 PM", "16:30 PM", "17:00 PM");
        
    }

    @FXML
    private void handleBookAppointment() {          // This controls the time and date function within the app
        LocalDate date = datePicker.getValue();
        String time = timeSlots.getValue();

        if (date == null || time == null) {
            showAlert("Error", "Please select both a date and a time slot.");
            return;
        }

        // A portion of this code "promptForInput" was generated by AI
        // Prompts user for their First Name
        String firstName = promptForInput("Enter First Name", "Please enter your first name:");
        if (firstName == null || firstName.trim().isEmpty()) {
            showAlert("Error", "First name is required.");
            return;
        }

        // A portion of this code "promptForInput" was generated by AI
        // Prompts user for their Last Name
        String lastName = promptForInput("Enter Last Name", "Please enter your last name:");
        if (lastName == null || lastName.trim().isEmpty()) {
            showAlert("Error", "Last name is required.");
            return;
        }

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            // Check if the booking already exists (removes problem of duplicates)
            String checkQuery = "SELECT COUNT(*) FROM bookings WHERE booking_date = ? AND booking_time = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkQuery)) {
                checkStmt.setDate(1, Date.valueOf(date));
                checkStmt.setString(2, time);
                ResultSet rs = checkStmt.executeQuery();
                if (rs.next() && rs.getInt(1) > 0) {
                    showAlert("Error", "This date and time slot is already booked.");
                    return;
                }
            }

            // This continues with booking if no duplicate is found
            String insertQuery = "INSERT INTO bookings (first_name, last_name, booking_date, booking_time) VALUES (?, ?, ?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertQuery)) {
                insertStmt.setString(1, firstName);
                insertStmt.setString(2, lastName);
                insertStmt.setDate(3, Date.valueOf(date));
                insertStmt.setString(4, time);
                insertStmt.executeUpdate();
                showAlert("Booking Confirmed", "Your appointment has been booked for " + date + " at " + time);
            }
        } catch (SQLException e) {
            showAlert("Database Error", "Failed to book appointment: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Clear the selections after booking
            datePicker.setValue(null);
            timeSlots.setValue(null);
        }
    }

    @FXML
    private void handleCancelAppointment() {          // Appointment Cancellation Function
        LocalDate date = datePicker.getValue();
        String time = timeSlots.getValue();

        if (date == null || time == null) {
            showAlert("Error", "Please select both a date and a time slot to cancel.");
            return;
        }

        // A portion of this code "promptForInput" was generated by AI
        // Ask user for their First Name
        String firstName = promptForInput("Enter First Name", "Please enter your first name:");
        if (firstName == null || firstName.trim().isEmpty()) {
            showAlert("Error", "First name is required.");
            return;
        }
        
        // A portion of this code "promptForInput" was generated by AI
        // Ask user for their Last Name
        String lastName = promptForInput("Enter Last Name", "Please enter your last name:");
        if (lastName == null || lastName.trim().isEmpty()) {
            showAlert("Error", "Last name is required.");
            return;
        }

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            // Cancel appointment based on user's name, date, and time
            String deleteQuery = "DELETE FROM bookings WHERE first_name = ? AND last_name = ? AND booking_date = ? AND booking_time = ?";
            try (PreparedStatement stmt = conn.prepareStatement(deleteQuery)) {
                stmt.setString(1, firstName);
                stmt.setString(2, lastName);
                stmt.setDate(3, Date.valueOf(date));
                stmt.setString(4, time);
                int rowsAffected = stmt.executeUpdate();

                if (rowsAffected > 0) {
                    showAlert("Appointment Cancelled", "Your appointment for " + date + " at " + time + " has been cancelled.");
                } else {
                    showAlert("Cancellation Error", "No appointment found for the selected details.");
                }
            }
        } catch (SQLException e) {
            showAlert("Database Error", "Failed to cancel appointment: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Clear the selections after cancelling
            datePicker.setValue(null);
            timeSlots.setValue(null);
        }
    }

    // This section onwards until the next line of comments was generated by AI.

    /**
     * Prompts the user for input using a TextInputDialog.
     *
     * @param title   The title of the dialog.
     * @param message The message displayed in the dialog.
     * @return The user's input as a String, or null if canceled.
     */


    private String promptForInput(String title, String message) {   // This makes an input text box where the user can enter details.
        TextInputDialog dialog = new TextInputDialog();
        dialog.setTitle(title);
        dialog.setHeaderText(null);
        dialog.setContentText(message);

        Optional<String> result = dialog.showAndWait();
        return result.orElse(null); // Return input or null if canceled
    }

    private void showAlert(String title, String message) {       // This is used to show information to the user.
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    ///////////////////////////////////////////////////////////////////////////////////  

    @FXML
    private void handleBackToHome() throws IOException {       // Return to the home page
        App.setRoot("homepage");
    }
}
